services:
  - type: web
    name: poshan-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install flask flask-cors openpyxl gunicorn PyJWT "pandas<3"
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://YOUR-VERCEL-APP.vercel.app
